#ifndef __CRAFT_SHOP_H
#define __CRAFT_SHOP_H
#define CRAFT_SHOP_INHERIT "/std/shops/craft_shop"
#define CRAFT_SHOP_CONTROLLER "/std/shops/craft_shop_controller"
#define CRAFT_SHOP_MAX_NAME_LENGTH 50
#define CRAFT_SHOP_MAIN_SAVE_FILE 1
#define CRAFT_SHOP_DATA_SAVE_FILE 2
#define CRAFT_SHOP_REMOVE_DATA_SAVE_FILE 3
#define CRAFT_CATEGORY_STATE_NOMINATING 1
#define CRAFT_CATEGORY_STATE_VOTING     2
#define CRAFT_CATEGORY_STATE_ACCEPTED   3
#define CRAFT_CATEGORY_STATE_DELETEING  4
#define CRAFT_CATEGORY_CHOICE_YES 1
#define CRAFT_CATEGORY_CHOICE_NO 2
#define CRAFT_CATEGORY_CHOICE_ABSTAIN 3
#define CRAFT_CATEGORY_ERROR -1
#define CRAFT_SHOP_EXPRESSION_HELP_DIR "/doc/furniture/expressions/"
#endif