#ifndef __NEWSPAPER_HANDLER
#define __NEWSPAPER_HANDLER
#define NEWSPAPER_ARCHIVE_EVENT_NO_PAPERS "no_papers"
#define NEWSPAPER_ARCHIVE_EVENT_LIST "list"
#define NEWSPAPER_ARCHIVE_EVENT_INVALID_PAPER "invalid_paper"
#define NEWSPAPER_ARCHIVE_EVENT_INVALID_EDITION "invalid_edition"
#define NEWSPAPER_ARCHIVE_EVENT_TOO_POOR "too_poor"
#define NEWSPAPER_ARCHIVE_EVENT_MOVE_PAPER "move_paper"
#define NEWSPAPER_ARCHIVE_EVENT_BOUGHT "bought"
#endif