#ifndef __EXPRESSIONS_H
#define __EXPRESSIONS_H
#define EXPRESSION_TYPE_INTEGER  1
#define EXPRESSION_TYPE_STRING   2
#define EXPRESSION_TYPE_ARRAY    3
#define EXPRESSION_TYPE_MAPPING  4
#define EXPRESSION_TYPE_FLOAT    5
#define EXPRESSION_TYPE_OPERATOR 6
#define EXPRESSION_TYPE_BOOLEAN  7
#define EXPRESSION_TYPE_VARIABLE 8
#define EXPRESSION_TYPE_MONEY    9
#define EXPRESSION_TYPE_FUNCTION 10
#define EXPRESSION_TYPE_SPECIAL  11
#define EXPRESSION_TYPE_FUNCTION_VARIABLE 12
#define EXPRESSION_TYPE_USER_FUNCTION 13
#define EXPRESSION_TYPE_OBJECT   14
#define EXPRESSION_TYPE_ARRAY_NULL   15
#define EXPRESSION_TYPE_ARRAY_OFFSET  20
#define EXPRESSION_TYPE_ERROR    -1
#ifndef EXPRESSION_NO_CLASSES
class parse_node {
   int type;
   mixed value;
   mixed* tree;
}
#endif
#endif