#ifndef __LIAISON_H
#define __LIAISON_H
#define LIAISON                "/d/liaison/"
#define LIAISON_MASTER         LIAISON + "master"
#define HANDLERS               LIAISON + "handlers/"
#define HELPERS                LIAISON + "helpers/"
#define IDEAS                  LIAISON + "ideas/"
#define ITEMS                  LIAISON + "items/"
#define NEWBIE                 LIAISON + "NEWBIE/"
#define SECURE                 LIAISON + "secure/"
#define TOYS                   LIAISON + "TOYS/"
#define UTILS                  LIAISON + "utils/"
#define WEB                    LIAISON + "public_html/"
#define SAVE_DIR               "/save/"
#define SAVE                   SAVE_DIR + "liaison/"
#define LIAISON_DOMAIN_INFO    SECURE + "domain_info.txt"
#define DOC_DIR                "/doc/creator/liaison/"
#define POLICY                 DOC_DIR + "policy/"
#define NEWBIE_CREATOR         NEWBIE + "CREATOR/"
#define NEWBIE_CHARS           NEWBIE + "chars/"
#define NEWBIE_DOC             NEWBIE + "doc/"
#define NEWBIE_ITEMS           ITEMS + "NEWBIE/"
#define NEWBIE_SAVE            NEWBIE + "save/"
#define TOYS_IDEAS             TOYS + "ideas/"
#endif