#ifndef __TERRAIN_MAP_H
#define __TERRAIN_MAP_H
#define TERRAIN_MAP_WORLD_MAP "/obj/handlers/world_map"
#define TERRAIN_MAP              "/std/room/inherit/terrain_map/"
#define TERRAIN_MAP_FEATURE_LOCAL  TERRAIN_MAP + "feature_local"
#define TERRAIN_MAP_SIMPLE_FEATURE_BASE  TERRAIN_MAP + "simple_feature"
#define TERRAIN_MAP_FEATURE_BASE  TERRAIN_MAP + "feature_base"
#define TERRAIN_MAP_DISTANCE_BASE  TERRAIN_MAP + "distance_str"
#define TERRAIN_MAP_REGION_RECTANGULAR  TERRAIN_MAP + "region_rect"
#define TERRAIN_MAP_REGION_POLYGON  TERRAIN_MAP + "region_poly"
#define TERRAIN_MAP_REGION_LINE  TERRAIN_MAP + "region_line"
#define TERRAIN_MAP_HANDLER_BASE  TERRAIN_MAP + "handler_base.c"
#define TERRAIN_MAP_FACTORY     TERRAIN_MAP + "factory.c"
#define TERRAIN_MAP_FACTORY_BASE     TERRAIN_MAP + "factory_base.c"
#define TERRAIN_MAP_ROOM_BASE     TERRAIN_MAP + "terrain_room.c"
#define TERRAIN_MAP_OUTSIDE_BASE  TERRAIN_MAP + "outside_base.c"
#define TERRAIN_MAP_WATER_OUTSIDE_BASE  TERRAIN_MAP + "water_outside_base.c"
#define TERRAIN_MAP_WATER_INSIDE_BASE  TERRAIN_MAP + "water_inside_base.c"
#define TERRAIN_MAP_INSIDE_BASE   TERRAIN_MAP + "inside_base.c"
#define TERRAIN_MAP_AIR_BASE TERRAIN_MAP + "air_base.c"
#define TERRAIN_MAP_ONE_MILE 73920
#define TERRAIN_MAP_HALF_MILE 36960
#define TERRAIN_MAP_GRID_SIZE (7 * TERRAIN_MAP_ONE_MILE)
#define TERRAIN_MAP_IN_LOOK_PROP "terrain map look"
#define TERRAIN_MAP_LONG_JUMP_PROPERTY "terrain map jump"
#define TERRAIN_MAP_WHOLE_SENTANCE_FLAG 1
#define TERRAIN_MAP_BLOCKING_FLAG       2
#define TERRAIN_MAP_JOURNEY_EXIT "journey "
#define TERRAIN_MAP_WALK_EXIT "walk "
#define TERRAIN_MAP_DEFAULT_AIR_ROOM "/room/air_terrain"
class coord {
   int x;
   int y;
   int z;
}
#define TERRAIN_MAP_WORLD_BOUNDARY (56 * TERRAIN_MAP_ONE_MILE)
#define TERRAIN_MAP_WORLD_REGION_SIZE 15
#define TERRAIN_MAP_WORLD_REGION_BOUNDARY (TERRAIN_MAP_WORLD_REGION_SIZE * BOUNDARY)
#define TERRAIN_MAP_WORLD_OFFSET (100 * TERRAIN_MAP_WORLD_BOUNDARY)
#define TERRAIN_MAP_WORLD_REGION_WIDTH 15
#define TERRAIN_MAP_WORLD_PIXEL_WIDTH 768
#define TERRAIN_MAP_WORLD_LOW_X (-(TERRAIN_MAP_WORLD_PIXEL_WIDTH / 2) * TERRAIN_MAP_GRID_SIZE * 10)
#define TERRAIN_MAP_WORLD_LOW_Y (-(TERRAIN_MAP_WORLD_PIXEL_WIDTH / 2) * TERRAIN_MAP_GRID_SIZE * 10)
#define TERRAIN_MAP_WORLD_HIGH_X ((TERRAIN_MAP_WORLD_PIXEL_WIDTH / 2) * TERRAIN_MAP_GRID_SIZE * 10)
#define TERRAIN_MAP_WORLD_HIGH_Y ((TERRAIN_MAP_WORLD_PIXEL_WIDTH / 2) * TERRAIN_MAP_GRID_SIZE * 10)
#define TERRAIN_MAP_ROOM_EXACT 0
#define TERRAIN_MAP_ROOM_MAP   1
#define TERRAIN_MAP_ROOM_CLIMB 2
#endif